language: c++
compiler: gcc
dist: trusty
install: true
cache: false
addons:
  apt:
    packages:
      - python3.4
branches:
  only:
    - travisci
script:
  - du -h $HOME | grep '^[0-9\.]\+G' || true
  - df -h .
  - $(pwd)/scripts/travis-setup.sh $(pwd)
